### ISSUE TITLE
Routes broken - artisan route:list - Yab\Quary\Models\Public does not exist

### ISSUE THREAD

**Issue by alexstudle** [YABhq/Quantum#1]
Hello dear Quantum Team,

this project seems very interresting ! I wanted to give it a try with a simple fresh install.

I followed all your steps (installed the project with composer as shown in your tutorial) and even run "php artisan quarx:setup", but it seems like certain routes are broken....

When I try to login, the login-views is correctly shown but the POST is redirected to "localhost/login" instead of "localhost/quantum/public/login".

So I wanted to check the routes myself with "php artisan route:list" but it returns me this error:
![image](https://cloud.githubusercontent.com/assets/19488087/24138881/41e71ff6-0e1a-11e7-8942-f5b586e578c9.png)

Am I doing something wrong ? Is it possible to fix this ?

Thank you :),
Alex

**Comment by mlantz** [comment]
Hey, so Quantum is essentially Laravel with Quarx added and all the setup steps done for you. You dont need to run setup with Quantum. I did just discover some dead routes though in the default setup. I'll release the fix this morning, but with Quantum you dont need to do anything to set it up, all you need to do is run the migration and everything should work out of the box.

**Comment by alexstudle** [comment]
Hi, thanks for your quick answer !
All clear now, no setup needed.
I'll try another intall after your release.
